package pl.zenit.tuqan.execution.parameters;

/** auto-generated by Tuqan v2.1 */
public class TuqanBasicParameters {
    
    private final boolean addId;
    private final int indentSize;
    private final String targetJavaVersion;
    private final boolean cleanOutput;
    private final boolean skipTests;
    private final boolean debug;
    
    public TuqanBasicParameters(boolean addId, int indentSize, String targetJavaVersion, boolean cleanOutput, boolean skipTests, boolean debug) {
        this.addId = addId;
        this.indentSize = indentSize;
        this.targetJavaVersion = targetJavaVersion;
        this.cleanOutput = cleanOutput;
        this.skipTests = skipTests;
        this.debug = debug;
    }
    
    public boolean getAddId() {
        return addId;
    }
    
    public int getIndentSize() {
        return indentSize;
    }
    
    public String getTargetJavaVersion() {
        return targetJavaVersion;
    }
    
    public boolean getCleanOutput() {
        return cleanOutput;
    }
    
    public boolean getSkipTests() {
        return skipTests;
    }

    public boolean isDebug() {
        return debug;
    }

    public TuqanBasicParameters withAddId(boolean addId) {
        return new TuqanBasicParameters (addId, indentSize, targetJavaVersion, cleanOutput, skipTests, debug);
    }

    public TuqanBasicParameters withIndentSize(int indentSize) {
        return new TuqanBasicParameters (addId, indentSize, targetJavaVersion, cleanOutput, skipTests, debug);
    }
    
    public TuqanBasicParameters withTargetJavaVersion(String targetJavaVersion) {
        return new TuqanBasicParameters (addId, indentSize, targetJavaVersion, cleanOutput, skipTests, debug);
    }
    
    public TuqanBasicParameters withCleanOutput(boolean cleanOutput) {
        return new TuqanBasicParameters (addId, indentSize, targetJavaVersion, cleanOutput, skipTests, debug);
    }
    
    public TuqanBasicParameters withSkipTests(boolean skipTests) {
        return new TuqanBasicParameters (addId, indentSize, targetJavaVersion, cleanOutput, skipTests, debug);
    }

    public TuqanBasicParameters withDebug(boolean debug) {
        return new TuqanBasicParameters (addId, indentSize, targetJavaVersion, cleanOutput, skipTests, debug);
    }

    public static TuqanBasicParametersBuilder builder() {
        return new TuqanBasicParametersBuilder();
    }

    public static class TuqanBasicParametersBuilder {
        
        private TuqanBasicParametersBuilder() {}
        
        private boolean addId;
        private int indentSize;
        private String targetJavaVersion;
        private boolean cleanOutput;
        private boolean skipTests;
        private boolean debug;

        public TuqanBasicParametersBuilder addId(boolean addId) {
            this.addId = addId;
            return this;
        }

        public TuqanBasicParametersBuilder indentSize(int indentSize) {
            this.indentSize = indentSize;
            return this;
        }
        
        public TuqanBasicParametersBuilder targetJavaVersion(String targetJavaVersion) {
            this.targetJavaVersion = targetJavaVersion;
            return this;
        }
        
        public TuqanBasicParametersBuilder cleanOutput(boolean cleanOutput) {
            this.cleanOutput = cleanOutput;
            return this;
        }
        
        public TuqanBasicParametersBuilder skipTests(boolean skipTests) {
            this.skipTests = skipTests;
            return this;
        }

        public TuqanBasicParametersBuilder debug(boolean debug) {
            this.debug = debug;
            return this;
        }
        
        public TuqanBasicParameters build() {
            return new TuqanBasicParameters (addId, indentSize, targetJavaVersion, cleanOutput, skipTests, debug);
        }
        
    }

} // end of class